### ISSUE TITLE
Not able to use IntelliJ IDE+Remote-Robot framework with github actions

### ISSUE THREAD

**Issue by zcervink** [JetBrains/intellij-ui-test-robot#1]
Several attempts were made to get the IntelliJ IDE+Remote-Robot work with github actions, the IDE does not start on any OS (LINUX, WIN, OS X) - tested on localhost, the run of the UI tests works on localhost, but not in github actions.

PR drafts to create new github actions to run the UI tests:
- https://github.com/redhat-developer/intellij-quarkus/pull/258
- https://github.com/redhat-developer/intellij-quarkus/pull/301
- https://github.com/redhat-developer/intellij-quarkus/pull/304

**Comment by nizienko** [comment]
Could you please check if the IDE can start with `runIde` task?

**Comment by nizienko** [comment]
Sorry, I don't have experience with github actions, I've looked at logs:
on linux 
```
  Test executionError FAILED

  com.intellij.remoterobot.utils.WaitForConditionTimeoutException: Exceeded timeout (PT2S) for condition function (Failed to find 'Welcome To IntelliJ IDEA Dialog' by 'FlatWelcomeFrame type' in 2s)
```
that could mean that Ide started, `robot-sever-plugin` was able to receive the the request to find a welcome frame but was not success finding it in 2 sec. If the Ide hadn't started there would be a some timeout exception. Is there any logs left from the Ide? Seems like the Ide failed to be rendered on the screen.

on windows:
```
Run ./gradlew runIdeForUiTests -PideaVersion=2020.1 &
ParserError: D:\a\_temp\a1507db0-0323-4483-b4f3-e9de5b12e2ff.ps1:7
Line |
   7 |  while [ $started -ne 0 ]; do
     |       ~
     | Missing opening '(' after keyword 'while'.

Error: Process completed with exit code 1.
```
seems that in powershell it should be `()` instead of `[]` in the `while` expression

and on mac it's hard to say as it was just `Error: The operation was canceled.` 
Or maybe I watch it wrong place?

**Comment by zcervink** [comment]
@nizienko I have updated the windows PR for PowerShell. The syntax issues are gone. Now it has the same behavior as the OS X version and I do know what happened. Both OS X and windows PRs starts first process (**./gradlew runIdeForUiTests**) and after that it waits in the loop until the Idea started and shows its UI (= it checks whether the **localhost:8082** is available using **curl**). After that the loop ends and the **./gradlew integrationTest** starts.

The issue is (and the reason for this github issue is), that the IDE never starts, the **localhost:8082** is never available and the loop never ends (everything is terminated after a long long time - thats the reason you see the **Error: The operation was canceled**)

The linux PR is little bit trickier - I have created this issue in the time the linux PR has exactly the same issue as the OS X (and windows after the PowerShell fixes). Since then there has been sever commits pushed to the PR and now it looks like the Ide starts and everything fails because of issue in my UI test (that I will resolve by myself). The question is, why does the linux PR starts the IntelliJ (I am not an author of the PR, probably I will have to write the author).

**Comment by fxnm** [comment]
The problem is that the task runIdeForUiTest or runIde is not provided with a graphical user interface when executed in Github Actions and therefore does not start.
The solution to this problem is to run the application headless. This can be done with e.g. xvfb.
`xvfb-run gradle runUiTests` (on linux)
This solved the problem of the missing graphical user interface but after that I had the problem that I could not connect to the IDE running in runIDEforUITest, which resulted in an infinite pause for the IDE.

**Comment by fxnm** [comment]
Hello,
I think I need to clarify something here.

The problem is that when you try tasks like `runIde` or `runIdeForUiTests` in an environment without a graphical user interface, they don't start with the error no graphical user interface.

This problem can be solved by using (under Linux) a program like `xvfb`, which simulates a display. If you now start tasks like `runIde` or `runIdeForUiTests` with `xvfb`, they execute but the ide does not start. 
Because when the Ide is starting for the first time, the terms and conditions must be accepted and the sharing of data must be allowed or prohibited. Only then does the Ide start normally.

Under linux this can be done with the following commands:
#### Disable IntelliJ data sharing
```
RUN set -x \
  && dir=/root/.local/share/JetBrains/consentOptions \
  && mkdir -p "$dir" \
  && echo -n "rsch.send.usage.stat:1.1:0:$(date +%s)000" > "$dir/accepted"
```

#### Accept End User Agreement/privacy policy
```
RUN set -x \
  && dir="/root/.java/.userPrefs/jetbrains/_!(!!cg\"p!(}!}@\"j!(k!|w\"w!'8!b!\"p!':!e@==" \
  && mkdir -p "$dir" \
  && echo '<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n\
<!DOCTYPE map SYSTEM "http://java.sun.com/dtd/preferences.dtd">\n\
<map MAP_XML_VERSION="1.0">\n\
  <entry key="accepted_version" value="2.1"/>\n\
  <entry key="eua_accepted_version" value="1.1"/>\n\
  <entry key="privacyeap_accepted_version" value="2.1"/>\n\
</map>' > "$dir/prefs.xml" \
  && cat "$dir/prefs.xml"
```

_Feel free to optimise these commands :)_

If the commands have now been executed and a task is now started with xvfb, it will start normally and function properly!

Unfortunately, this cannot be implemented directly in Github Actions, as the commands (access on /root/...) cannot be executed.
However, this can be implemented using a separate docker container.
For an example, see [CodeTester-IDEA](https://github.com/fxnm/CodeTester-IDEA/pull/19).

Perhaps this can be added to the documentation of the ui test robot.

**Comment by abrooksv** [comment]
Try:
```
systemProperty("jb.privacy.policy.text", "<!--999.999-->")
```

https://github.com/JetBrains/intellij-community/blob/0c2a12b254102e25093117f7b8d273cd986c150e/platform/platform-impl/src/com/intellij/ide/gdpr/EndUserAgreement.java#L218

**Comment by nizienko** [comment]
@fxnm, @abrooksv thank you for helping here! I've added your answer to the [FAQ](https://github.com/JetBrains/intellij-ui-test-robot/blob/master/ui-test-example/FAQ.md)

**Comment by nizienko** [comment]
Hello, I've managed to launch our test examples on all 3 OSs using Github Actions.
https://github.com/JetBrains/intellij-ui-test-robot/blob/master/.github/workflows/runTest.yml

**Comment by 2chiefk** [comment]
> Several attempts were made to get the IntelliJ IDE+Remote-Robot work with github actions, the IDE does not start on any OS (LINUX, WIN, OS X) - tested on localhost, the run of the UI tests works on localhost, but not in github actions.
> 
> PR drafts to create new github actions to run the UI tests:
> 
> * [Add integration tests for Linux redhat-developer/intellij-quarkus#258](https://github.com/redhat-developer/intellij-quarkus/pull/258)
> * [Add code to run UI tests on os x to the '.github/workflows/ci.yml' redhat-developer/intellij-quarkus#301](https://github.com/redhat-developer/intellij-quarkus/pull/301)
> * [Add code to run UI tests on windows to the .github/workflows/ci.yml redhat-developer/intellij-quarkus#304](https://github.com/redhat-developer/intellij-quarkus/pull/304)

This is some of the stuff we all forget
